#!/usr/bin/env bash

#: exec_target = cli

## Initialize/reinstall site
##
## Usage: fin init-site

# Abort if anything fails
set -e

#-------------------------- Settings --------------------------------

# PROJECT_ROOT and DOCROOT are set as env variables in cli
DOCROOT_PATH="${PROJECT_ROOT}/${DOCROOT}"

#-------------------------- Helper functions --------------------------------

# Console colors
red='\033[0;31m'
green='\033[0;32m'
green_bg='\033[1;97;42m'
yellow='\033[1;33m'
NC='\033[0m'

echo-red () { echo -e "${red}$1${NC}"; }
echo-green () { echo -e "${green}$1${NC}"; }
echo-green-bg () { echo -e "${green_bg}$1${NC}"; }
echo-yellow () { echo -e "${yellow}$1${NC}"; }

#-------------------------- Functions --------------------------------

composer_install ()
{
	cd "$PROJECT_ROOT"
	echo-green "Installing dependencies..."
	export COMPOSER_PROCESS_TIMEOUT=2000
	export COMPOSER_MEMORY_LIMIT=-1
	composer clear-cache --no-interaction
	composer install --no-interaction
}

# blt setup
blt_setup ()
{
	cd "$DOCROOT_PATH"

	# Allow exiting to configure project before install.
	echo
	echo-yellow "Going to run BLT setup..."
	echo -e "Press ${yellow}Ctrl+C${NC} if you want to make changes to ${yellow}blt.yml${NC}."
	echo -e "After configuring your ${yellow}blt.yml${NC}, run ${yellow}fin blt setup${NC} to complete your setup."
	echo
	sleep 30

	echo-green "Running BLT setup..."
	../vendor/bin/blt setup --no-interaction
}

#-------------------------- Execution --------------------------------

# Project initialization steps
composer_install
blt_setup

echo
echo -e "Open ${yellow}http://${VIRTUAL_HOST}${NC} in your browser to verify the setup."
echo-yellow "Look for admin login credentials in the output above."
