#!/usr/bin/env bash

## Run blt setup commands to prepare your local site for
## development.
##
## Usage: fin init

# Abort if anything fails
set -e
#-------------------------- Settings --------------------------------

DOCROOT_PATH="${PROJECT_ROOT}/${DOCROOT}"

#-------------------------- END: Settings --------------------------------

#-------------------------- Helper functions --------------------------------

# Console colors
red='\033[0;31m'
green='\033[0;32m'
green_bg='\033[42m'
yellow='\033[1;33m'
NC='\033[0m'

echo-red () { echo -e "${red}$1${NC}"; }
echo-green () { echo -e "${green}$1${NC}"; }
echo-green-bg () { echo -e "${green_bg}$1${NC}"; }
echo-yellow () { echo -e "${yellow}$1${NC}"; }

# Copy a settings file.
# Skips if the destination file already exists.
# @param $1 source file
# @param $2 destination file
copy_settings_file()
{
	local source="$1"
	local dest="$2"

	if [[ (-f $dest) || (-d $dest) ]]; then
		echo-yellow "${dest} already in place."
	elif [[ -d $source ]]; then
		echo "Copying to ${dest}..."
		cp -r $source $dest
    else
        echo "Copying to ${dest}..."
		cp $source $dest
	fi
}

#-------------------------- END: Helper Functions --------------------------------

#-------------------------- Functions --------------------------------

# Initialize local settings files
init_local_settings ()
{
  copy_settings_file "${PROJECT_ROOT}/blt/example.local.blt.yml" "${PROJECT_ROOT}/blt/local.blt.yml"
}

#-------------------------- END: Functions --------------------------------

#-------------------------- Execution --------------------------------

# Initialize stack
fin project start

#Initialize local settings
init_local_settings

# Install project requirements
fin exec composer clear-cache
fin exec COMPOSER_PROCESS_TIMEOUT=2000
fin exec COMPOSER_MEMORY_LIMIT=-1 composer install

# Set up blt
cd $DOCROOT_PATH
fin blt blt:init:settings -n
fin blt drupal:install -n

echo
echo -en "${green_bg} DONE! ${NC}"
echo
echo -e "Open ${yellow}http://${VIRTUAL_HOST}${NC} in your browser to verify the setup."
